version: '3.8'
services:
  web:
    # build: <chemin_vers_dossier_contenant_dockerfile>
    build: .
    volumes:
      - ./src/critique_film:/app/src/critique_film
    ports:
    # - <HOST_PORT>:<CONTAINER_PORT>
      - 5000:5000




  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: critiques_de_films
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: